# Zizmor configuration file
rules:
  unpinned-uses:
    config:
      policies:
        # Zizmor defaults to requiring pinning by immutable hashes.
        # Allow pinning by refs for trusted organisations.
        # https://docs.zizmor.sh/audits/#rulesunpinned-usesconfigpolicies
        actions/*: ref-pin
