name: Lint
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    env:
      TERRAFORM_VERSION: 1.15.6
      TERRAFORM_DOCS_VERSION: 0.24.0
      TFLINT_VERSION: 0.63.1

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      # Needed for Prettier
      - uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@b480b8fcdaa6f2c577f8e4fa799e89e756bb7c93 # v6.2.2
        with:
          # https://github.com/terraform-linters/tflint/tags
          tflint_version: v${{ env.TFLINT_VERSION }}
          cache: true

      - name: Install terraform-docs
        run: |
          mkdir -p "/$HOME/.local/bin"
          curl -sfSL "https://terraform-docs.io/dl/v${TERRAFORM_DOCS_VERSION}/terraform-docs-v${TERRAFORM_DOCS_VERSION}-linux-amd64.tar.gz" | \
            tar -zx -C "/$HOME/.local/bin" terraform-docs

      - name: Run prek (pre-commit)
        uses: j178/prek-action@e98a699c41eb69ab013a45817a0406469a748f8d # v2.0.5

      - name: Validate Terraform
        run: |
          terraform init -backend=false
          terraform validate
